"""baseline — schema snapshot at Alembic adoption

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-19

This revision marks the schema produced by ``Base.metadata.create_all`` at the
moment Alembic was adopted, so it performs **no DDL**.

Why no DDL: Tetra Host already had a live production database (and dev/test
databases) whose schema was materialised by ``create_all`` plus the legacy
in-place upgrader in ``app.db.session``. Adopting Alembic by replaying a full
"create everything" baseline against those databases would fail on the
already-existing tables. Instead:

* Fresh / test databases are materialised by ``create_all`` (the fast path) and
  then **stamped** at ``head`` — see ``app.db.session._stamp_alembic_head_if_absent``.
* Existing databases are auto-stamped at ``head`` on their next boot.
* Every *future* schema change gets its own autogenerated revision layered on
  top of this baseline and is applied with ``alembic upgrade head`` at deploy
  time — replacing the hand-rolled ``_upgrade_existing_schema`` ALTER hacks.
"""

from __future__ import annotations

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Intentionally empty: the baseline schema is created by create_all and this
    # revision only records the starting point. See module docstring.
    pass


def downgrade() -> None:
    pass
