/**
 * Central icon registry — Font Awesome. Import icons from here (not directly from the FA
 * packages) so the whole console shares one consistent, curated icon set.
 */
import { faGithub } from "@fortawesome/free-brands-svg-icons"
import {
  faArrowRightFromBracket,
  faArrowsRotate,
  faArrowUpRightFromSquare,
  faBan,
  faBox,
  faCircleCheck,
  faCircleExclamation,
  faCirclePlay,
  faCircleStop,
  faCloud,
  faEnvelope,
  faGaugeHigh,
  faGlobe,
  faHourglassHalf,
  faLayerGroup,
  faMagnifyingGlass,
  faPlus,
  faRocket,
  faServer,
  faSliders,
  faTrash,
  faTriangleExclamation,
  faUsers,
  faUserShield,
} from "@fortawesome/free-solid-svg-icons"

export {
  faArrowRightFromBracket,
  faArrowsRotate,
  faArrowUpRightFromSquare,
  faBan,
  faBox,
  faCircleCheck,
  faCircleExclamation,
  faCirclePlay,
  faCircleStop,
  faCloud,
  faEnvelope,
  faGaugeHigh,
  faGithub,
  faGlobe,
  faHourglassHalf,
  faLayerGroup,
  faMagnifyingGlass,
  faPlus,
  faRocket,
  faServer,
  faSliders,
  faTrash,
  faTriangleExclamation,
  faUsers,
  faUserShield,
}
